apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
data:
    SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5433/url_shortener"
    SPRING_DATA_REDIS_HOST: "localhost"
    SPRING_DATA_REDIS_PORT: "6380"
    URL_BASE_DOMAIN: "http://localhost:8080"