version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: url-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dinusha@020040225.
      POSTGRES_DB: url_shortener
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: url-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

volumes:
  pg-data: